name: Build .NET Framework 4.7.2

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore NuGet packages
        run: nuget restore SSSystemGenerator/SSSystemGenerator.sln

      - name: Build solution
        run: msbuild SSSystemGenerator/SSSystemGenerator.sln /p:Configuration=Release /p:OutputPath=..\..\SGTExe\

      - name: Verify build output
        run: |
          powershell -command "Get-ChildItem -Recurse"

      - name: Unlock EXE before upload
        run: |
          powershell -command "Stop-Process -Name '.SSSystemGenerator' -ErrorAction SilentlyContinue"

      - name: Publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: BuildOutput
          path: SGTExe/**
          compression-level: 0
          overwrite: true
