name: Zip and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Enter version'
        required: true
        default: 'Vx.x.x'
      relaseDescription:
        description: 'Enter relase description'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up zip tool
        run: sudo apt-get install zip

      - name: Install UUID generator
        run: sudo apt-get install -y uuid-runtime

      - name: Create zip excluding specific folders
        run: |
          # Exclude multiple folders by specifying each one with -x
          zip -r SGT.zip ../ -x "../SGT/.idea/*" -x "../SGT/.run/*" -x "../SGT/.github/*" -x "../SGT/.SGTExe/*" -x "../SGT/SSSystemGenerator/*" -x "../SGT/src/*" -x "../SGT/.git/*" -x "../SGT/README.*" -x "../SGT/SGTExe/*.xml" -x "../SGT/SGTExe/*.pdb"

      - name: Zip SGTExe
        run: zip -r SGTExe.zip SGTExe -x "*.xml" "*.pdb"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: ${{ github.event.inputs.relaseDescription }}
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          draft: false
          prerelease: false

      - name: Upload SGTExe
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./SGTExe.zip
          asset_name: SGTExe.zip
          asset_content_type: application/zip

      - name: Upload SGT
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./SGT.zip
          asset_name: SGT.zip
          asset_content_type: application/zip
